const CONTACTO = {
  whatsapp: "",
  facebook: "",
  facebookBusqueda: "https://www.facebook.com/search/top?q=La%20Bendici%C3%B3n%20Macrobi%C3%B3tica%20Mercado%20Central",
  direccion: "Mercado Central de San José, entre avenidas Central y 1, calles 6 y 8",
  lat: 9.93515,
  lng: -84.08095,
  horario: [
    { dia: "Lunes", abre: "08:00", cierra: "18:00" },
    { dia: "Martes", abre: "08:00", cierra: "18:00" },
    { dia: "Miércoles", abre: "08:00", cierra: "18:00" },
    { dia: "Jueves", abre: "08:00", cierra: "18:00" },
    { dia: "Viernes", abre: "08:00", cierra: "18:00" },
    { dia: "Sábado", abre: "08:00", cierra: "17:00" },
    { dia: "Domingo", abre: null, cierra: null },
  ],
};

const CATEGORIAS = [
  { id: "capsulas", nombre: "Cápsulas", envase: "frasco", tinte: "#B5651D", nota: "Suplementos de origen vegetal" },
  { id: "champus", nombre: "Champús", envase: "botella", tinte: "#3F7D5A", nota: "Para el cabello y el cuero cabelludo" },
  { id: "hierbas", nombre: "Hierbas", envase: "bolsa", tinte: "#6E8B3D", nota: "Hierbas secas para infusión" },
  { id: "gotas", nombre: "Gotas", envase: "gotero", tinte: "#8F4A1C", nota: "Extractos y tinturas" },
  { id: "jabones", nombre: "Jabones", envase: "jabon", tinte: "#7A6A9B", nota: "Jabones artesanales" },
  { id: "tes", nombre: "Tés", envase: "caja", tinte: "#4F7A3A", nota: "Mezclas listas para preparar" },
  { id: "pomadas", nombre: "Pomadas", envase: "lata", tinte: "#2E6A6E", nota: "Para aplicar sobre la piel" },
];

const PRODUCTOS = [
  { id: "moringa", cat: "capsulas", nombre: "Cápsulas de moringa", etiqueta: "Moringa", tinte: "#6B8E23", disponible: true,
    descripcion: "Hoja de moringa deshidratada y molida, en cápsulas de origen vegetal. Frasco de 60 cápsulas.",
    uso: "Complemento nutricional que se usa tradicionalmente para apoyar las defensas y la energía del día a día.",
    modo: "Tomar 1 cápsula al día con el desayuno, o según la indicación del empaque. No exceder la dosis indicada." },
  { id: "ginkgo", cat: "capsulas", nombre: "Cápsulas de ginkgo biloba", etiqueta: "Ginkgo", tinte: "#B08A1E", disponible: true,
    descripcion: "Extracto de hoja de ginkgo biloba en cápsulas. Frasco de 60 cápsulas.",
    uso: "Se usa tradicionalmente como apoyo para la memoria y la concentración en épocas de estudio o trabajo intenso.",
    modo: "Tomar 1 cápsula al día con alimentos. Si toma anticoagulantes, consulte antes con su médico." },
  { id: "equinacea", cat: "capsulas", nombre: "Cápsulas de equinácea", etiqueta: "Equinácea", tinte: "#9B4F7A", disponible: true,
    descripcion: "Raíz y flor de equinácea en cápsulas. Frasco de 50 cápsulas.",
    uso: "Se usa tradicionalmente para apoyar las defensas en los cambios de clima.",
    modo: "Tomar 1 cápsula dos veces al día por periodos cortos, según la indicación del empaque." },
  { id: "cola-caballo", cat: "capsulas", nombre: "Cápsulas de cola de caballo", etiqueta: "Cola de caballo", tinte: "#5C7A2E", disponible: false,
    descripcion: "Planta cola de caballo deshidratada en cápsulas. Frasco de 60 cápsulas.",
    uso: "Se usa tradicionalmente como apoyo para fortalecer el cabello y las uñas.",
    modo: "Tomar 1 cápsula al día con agua, según la indicación del empaque." },

  { id: "champu-romero", cat: "champus", nombre: "Champú de romero", etiqueta: "Romero", tinte: "#3F7D5A", disponible: true,
    descripcion: "Champú con extracto de romero, sin sales agregadas. Botella de 400 ml.",
    uso: "Pensado para el cuidado del cuero cabelludo y como apoyo cuando hay caída del cabello.",
    modo: "Aplicar sobre el cabello húmedo, masajear el cuero cabelludo por 2 minutos y enjuagar. Uso diario." },
  { id: "champu-sabila", cat: "champus", nombre: "Champú de sábila", etiqueta: "Sábila", tinte: "#4E9A7A", disponible: true,
    descripcion: "Champú con gel de sábila natural. Botella de 400 ml.",
    uso: "Ayuda a hidratar el cabello y a calmar el cuero cabelludo reseco.",
    modo: "Aplicar sobre el cabello húmedo, hacer espuma y enjuagar. Se puede usar todos los días." },
  { id: "champu-ortiga", cat: "champus", nombre: "Champú de ortiga", etiqueta: "Ortiga", tinte: "#55703A", disponible: false,
    descripcion: "Champú con extracto de ortiga. Botella de 400 ml.",
    uso: "Para cabello graso y como apoyo cuando hay caída del cabello.",
    modo: "Aplicar sobre el cabello húmedo, dejar actuar 3 minutos y enjuagar. Usar de 3 a 4 veces por semana." },

  { id: "manzanilla", cat: "hierbas", nombre: "Manzanilla", etiqueta: "Manzanilla", tinte: "#C9A227", disponible: true,
    descripcion: "Flor de manzanilla seca para infusión. Bolsa de 50 g.",
    uso: "Infusión tradicional para relajarse, aliviar el dolor de cabeza leve y apoyar la digestión.",
    modo: "Una cucharadita en una taza de agua caliente. Reposar 5 minutos y colar. Hasta 3 tazas al día." },
  { id: "menta", cat: "hierbas", nombre: "Menta", etiqueta: "Menta", tinte: "#3C8C6E", disponible: true,
    descripcion: "Hoja de menta seca para infusión. Bolsa de 40 g.",
    uso: "Infusión refrescante que se usa tradicionalmente para el dolor de cabeza leve y la digestión pesada.",
    modo: "Una cucharadita en una taza de agua caliente. Reposar 5 minutos y colar. Hasta 3 tazas al día." },
  { id: "tilo", cat: "hierbas", nombre: "Tilo", etiqueta: "Tilo", tinte: "#A6922E", disponible: true,
    descripcion: "Flor de tilo seca para infusión. Bolsa de 40 g.",
    uso: "Infusión tradicional para relajarse por la noche y dormir mejor.",
    modo: "Una cucharadita en una taza de agua caliente, 30 minutos antes de dormir." },
  { id: "zacate-limon", cat: "hierbas", nombre: "Zacate de limón", etiqueta: "Zacate de limón", tinte: "#7D9A2A", disponible: true,
    descripcion: "Hoja de zacate de limón seca para infusión. Bolsa de 50 g.",
    uso: "Infusión aromática para el bienestar general y la digestión.",
    modo: "Una cucharada en una taza de agua caliente. Reposar 7 minutos y colar." },

  { id: "valeriana", cat: "gotas", nombre: "Gotas de valeriana", etiqueta: "Valeriana", tinte: "#7B4A8C", disponible: true,
    descripcion: "Extracto de raíz de valeriana en gotas. Frasco de 30 ml.",
    uso: "Se usa tradicionalmente para conciliar el sueño y calmar los nervios.",
    modo: "20 gotas en medio vaso de agua, 30 minutos antes de dormir. No combinar con alcohol ni sedantes." },
  { id: "propoleo", cat: "gotas", nombre: "Gotas de propóleo", etiqueta: "Propóleo", tinte: "#A4621C", disponible: true,
    descripcion: "Extracto de propóleo de abeja en gotas. Frasco de 30 ml.",
    uso: "Se usa tradicionalmente para apoyar las defensas y aliviar la garganta irritada.",
    modo: "10 gotas en agua o jugo, dos veces al día. No usar si tiene alergia a productos de abeja." },
  { id: "sauce-blanco", cat: "gotas", nombre: "Gotas de sauce blanco", etiqueta: "Sauce blanco", tinte: "#8C6B3E", disponible: true,
    descripcion: "Extracto de corteza de sauce blanco en gotas. Frasco de 30 ml.",
    uso: "Se usa tradicionalmente como apoyo para el dolor de cabeza y los dolores musculares leves.",
    modo: "15 gotas en agua hasta dos veces al día. No usar si es alérgico a la aspirina o si está embarazada." },

  { id: "jabon-avena", cat: "jabones", nombre: "Jabón de avena", etiqueta: "Avena", tinte: "#B39566", disponible: true,
    descripcion: "Jabón artesanal de avena y miel. Barra de 120 g.",
    uso: "Limpieza suave para piel sensible o reseca.",
    modo: "Hacer espuma con agua tibia, aplicar sobre la piel y enjuagar. Uso diario." },
  { id: "jabon-carbon", cat: "jabones", nombre: "Jabón de carbón activado", etiqueta: "Carbón", tinte: "#3D4542", disponible: true,
    descripcion: "Jabón artesanal con carbón activado. Barra de 120 g.",
    uso: "Limpieza profunda para piel grasa.",
    modo: "Aplicar en el rostro con agua tibia, masajear 1 minuto y enjuagar. Una o dos veces al día." },
  { id: "jabon-calendula", cat: "jabones", nombre: "Jabón de caléndula", etiqueta: "Caléndula", tinte: "#D0821E", disponible: true,
    descripcion: "Jabón artesanal con flor de caléndula. Barra de 120 g.",
    uso: "Limpieza suave que ayuda a calmar la piel irritada.",
    modo: "Hacer espuma con agua tibia, aplicar y enjuagar. Uso diario." },

  { id: "te-verde", cat: "tes", nombre: "Té verde", etiqueta: "Té verde", tinte: "#4F7A3A", disponible: true,
    descripcion: "Té verde en bolsitas. Caja de 25 bolsitas.",
    uso: "Bebida con cafeína natural para mantenerse alerta y concentrado.",
    modo: "Una bolsita en agua caliente (no hirviendo) por 3 minutos. Hasta 3 tazas al día, no en la noche." },
  { id: "te-jengibre", cat: "tes", nombre: "Té de jengibre y limón", etiqueta: "Jengibre", tinte: "#C07A1A", disponible: true,
    descripcion: "Mezcla de jengibre y limón en bolsitas. Caja de 20 bolsitas.",
    uso: "Se usa tradicionalmente para apoyar las defensas y entrar en calor.",
    modo: "Una bolsita en agua caliente por 5 minutos. Se puede endulzar con miel." },
  { id: "te-relajante", cat: "tes", nombre: "Té relajante de tilo y manzanilla", etiqueta: "Tilo y manzanilla", tinte: "#8A7A3C", disponible: true,
    descripcion: "Mezcla de tilo, manzanilla y zacate de limón. Caja de 20 bolsitas.",
    uso: "Para relajarse al final del día y dormir mejor.",
    modo: "Una bolsita en agua caliente por 5 minutos, antes de dormir." },

  { id: "arnica", cat: "pomadas", nombre: "Pomada de árnica", etiqueta: "Árnica", tinte: "#C2851C", disponible: true,
    descripcion: "Pomada con extracto de flor de árnica. Envase de 60 g.",
    uso: "Para golpes, moretones y dolores musculares.",
    modo: "Aplicar una capa delgada en la zona afectada y masajear suavemente, hasta 3 veces al día. No aplicar sobre heridas abiertas." },
  { id: "eucalipto", cat: "pomadas", nombre: "Pomada de eucalipto y alcanfor", etiqueta: "Eucalipto", tinte: "#2E6A6E", disponible: true,
    descripcion: "Pomada de eucalipto y alcanfor. Envase de 60 g.",
    uso: "Para dolores musculares después del ejercicio y para aplicar en el pecho cuando hay congestión.",
    modo: "Aplicar y masajear en la zona hasta que se absorba. No usar en niños menores de 2 años." },
  { id: "mentol", cat: "pomadas", nombre: "Pomada de mentol", etiqueta: "Mentol", tinte: "#3E8A8C", disponible: false,
    descripcion: "Pomada refrescante de mentol. Envase de 30 g.",
    uso: "Sensación de frescura para el dolor de cabeza leve y los músculos tensos.",
    modo: "Aplicar una pequeña cantidad en sienes, cuello u hombros. Evitar el contacto con los ojos." },
  { id: "pomada-calendula", cat: "pomadas", nombre: "Pomada de caléndula", etiqueta: "Caléndula", tinte: "#D08A1E", disponible: true,
    descripcion: "Pomada de flor de caléndula. Envase de 60 g.",
    uso: "Para calmar la piel irritada o reseca.",
    modo: "Aplicar una capa delgada sobre la piel limpia, dos o tres veces al día." },
];

const SINTOMAS = [
  { id: "dolor-cabeza", nombre: "Dolor de cabeza", icono: "cabeza",
    texto: "Para el dolor de cabeza leve se suelen recomendar infusiones de manzanilla o menta y algunas gotas.",
    productos: ["manzanilla", "menta", "sauce-blanco", "mentol"] },
  { id: "caida-cabello", nombre: "Caída del cabello", icono: "cabello",
    texto: "Champús de plantas y complementos que se usan tradicionalmente para fortalecer el cabello.",
    productos: ["champu-romero", "champu-ortiga", "cola-caballo", "champu-sabila"] },
  { id: "defensas", nombre: "Bajas defensas", icono: "escudo",
    texto: "Productos que se usan tradicionalmente para apoyar las defensas, sobre todo en cambios de clima.",
    productos: ["propoleo", "equinacea", "moringa", "te-jengibre"] },
  { id: "dormir", nombre: "Problemas para dormir", icono: "luna",
    texto: "Infusiones y gotas que ayudan a relajarse antes de dormir.",
    productos: ["valeriana", "tilo", "te-relajante", "manzanilla"] },
  { id: "concentracion", nombre: "Concentración y rendimiento mental", icono: "foco",
    texto: "Para épocas de estudio o trabajo intenso.",
    productos: ["ginkgo", "te-verde", "moringa"] },
  { id: "muscular", nombre: "Dolores musculares", icono: "musculo",
    texto: "Pomadas y gotas para dolores después del ejercicio o del trabajo.",
    productos: ["arnica", "eucalipto", "mentol", "sauce-blanco"] },
  { id: "prevencion", nombre: "Prevención general", icono: "brote",
    texto: "Productos para el bienestar del día a día.",
    productos: ["moringa", "te-jengibre", "te-verde", "zacate-limon"] },
];

const PREGUNTAS = [
  { p: "¿Los productos naturales tienen efectos secundarios?",
    r: "Sí, pueden tenerlos. Que un producto sea natural no significa que no tenga efectos. Lea la etiqueta, use la dosis indicada y suspenda el uso si nota alguna reacción. Si toma medicamentos, consulte antes con su médico." },
  { p: "¿Puedo combinar varios productos?",
    r: "Algunos se pueden combinar y otros no. Antes de hacerlo, escríbanos por WhatsApp y cuéntenos qué está usando. Si lleva un tratamiento médico, consulte también con su médico." },
  { p: "¿Cada cuánto debo usarlos?",
    r: "Depende de cada producto. La frecuencia está en la sección «Modo de uso» de cada ficha y en el empaque." },
  { p: "¿Hacen envíos?",
    r: "Escríbanos por WhatsApp con su pedido y le indicamos las opciones de entrega disponibles para su zona." },
  { p: "¿Los pueden usar niños y adultos mayores?",
    r: "Algunos productos no se recomiendan para niños, embarazadas o personas con ciertas condiciones de salud. Consulte en el local o por WhatsApp antes de usarlos, y con su médico de cabecera." },
  { p: "¿Cómo sé cuál producto me conviene?",
    r: "Use la sección «Síntomas» para ver sugerencias según lo que siente. Después confirme con nosotros en el local o por WhatsApp antes de comprar." },
];

const TESTIMONIOS = [
  { nombre: "Rosa M.", texto: "Llevo años comprando la pomada de árnica para las rodillas. Siempre me explican con paciencia cómo usar cada cosa." },
  { nombre: "Andrés V.", texto: "Estudio de noche y el té verde me acompaña. Ahora puedo ver el catálogo desde el celular antes de ir al Mercado." },
  { nombre: "Marta C.", texto: "Mi mamá compraba aquí y ahora compro yo. La atención sigue siendo igual de buena." },
  { nombre: "Diego S.", texto: "Después del gimnasio uso la pomada de eucalipto. Me la recomendaron en el local y me funcionó." },
  { nombre: "Lucía R.", texto: "Las gotas de valeriana me ayudaron a dormir mejor en época de exámenes." },
];
